# Use an official Nginx image from the Docker Hub
FROM nginx:alpine

# Remove the default Nginx website files
RUN rm -rf /usr/share/nginx/html/*

# Copy the website files to the Nginx directory
COPY ./public_html/ /usr/share/nginx/html

# Set permissions to ensure Nginx can serve the files
RUN chmod -R 755 /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
